name: Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group:
    "${{github.workflow}} @ ${{github.pull_request.head.label || github.head_ref
    || github.ref}}"
  cancel-in-progress: true

jobs:
  dotFiles:
    name: Dot File Quality
    uses: brobeson/SupportFileQuality/.github/workflows/support_files.yaml@v1
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Packages and Tools
        run: |
          npm install
          npm install --global vsce
      - name: Check for ES lint
        run: |
          npm ci
          npm run lint
      - if: runner.os == 'Linux'
        # cspell:ignore servernum
        name: Run Tests on Linux
        run: xvfb-run --auto-servernum npm test
      - if: runner.os != 'Linux'
        name: Run Tests on Windows & MacOS
        run: npm test
      - if: runner.os == 'Linux'
        name: Create a VSIX Package
        run: vsce package
      - if: runner.os == 'Linux'
        name: Verify the Package
        run: ./src/test/package_test.sh
