# Copyright 2023 brobeson

name: Static Analysis
on:
  workflow_dispatch:
  pull_request:
  push:

# From https://stackoverflow.com/a/72408109
# Create a group from the PR number, or the branch/tag name (if not a PR).
# Cancel in-progress runs if the PR, branch, or tag is updated.
concurrency:
  group:
    ${{github.workflow}}-${{github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

jobs:
  staticAnalysisDot:
    name: Support File Code Quality
    uses: brobeson/brobeson/.github/workflows/static_analysis_support_files.yaml@reusable_workflows
  staticAnalysisTs:
    name: TypeScript Code Quality
    uses: brobeson/brobeson/.github/workflows/static_analysis_support_files.yaml@reusable_workflows
