# Copyright 2023 brobeson

name: Static Analysis
on:
  pull_request:
  push:

# From https://stackoverflow.com/a/72408109
# Create a group from the PR number, or the branch/tag name (if not a PR).
# Cancel in-progress runs if the PR, branch, or tag is updated.
concurrency:
  group:
    ${{github.workflow}}-${{github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

jobs:
  CodeQuality:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Check for Markdown lint
        uses: nosborn/github-action-markdown-cli@v3
        with:
          files: .
          dot: true
          ignore_files: node_modules
      # - name: Check code formatting
      #   uses: creyD/prettier_action@v4.3
      #   with:
      #     dry: true
      #     prettier_options: >
      #       --check ./**/*.{md,json,ts,yaml,yml}
      # - name: Check spelling
      #   uses: streetsidesoftware/cspell-action@v2
      #   with:
      #     check_dot_files: true,
      #     root: .
      # Different ESLint actions in the marketplace kept throwing errors, so
      # just run it from the package.json script.
      - name: Check for ES lint
        run: |
          npm ci
          npm run lint
